# Generated by Django 4.2.7 on 2025-03-07 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_order', models.CharField(blank=True, max_length=15, null=True)),
                ('delivary_location', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.ManyToManyField(blank=True, related_name='order_id', to='products.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='products.user')),
            ],
        ),
    ]
