# Generated by Django 4.2.7 on 2025-03-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_history_user_id_alter_order_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='history',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.history'),
        ),
    ]
