# Generated by Django 4.2.7 on 2025-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_user_id_history_user_remove_history_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='history',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
