# Generated by Django 4.2.7 on 2025-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_order_history_order_location_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
